import { EventItem } from './types';

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: 'evt-ai-summit-2026',
    title: 'Thailand AI & Next-Gen Tech Summit 2026',
    description: 'มหกรรมสัมมนาเทคโนโลยีปัญญาประดิษฐ์ที่ยิ่งใหญ่ที่สุดแห่งปี รวบรวมผู้เชี่ยวชาญด้าน Generative AI, Machine Learning และ Cloud Computing ชั้นนำระดับโลก พร้อมเวิร์กช็อปและโชว์เคสผลงานนวัตกรรมกว่า 50 บูธ',
    category: 'Tech & AI',
    date: '2026-10-24',
    time: '09:00 - 18:00 น.',
    location: 'True Digital Park, Grand Hall ชั้น 3, กรุงเทพฯ',
    location_type: 'onsite',
    max_seats: 350,
    booked_seats: 218,
    price: 0,
    image_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80',
    organizer: 'Tech Innovators Network Thailand',
    organizer_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    tags: ['AI', 'Tech', 'Innovation', 'Machine Learning', 'Free'],
    featured: true,
    agenda: [
      { time: '09:00 - 09:30', title: 'ลงทะเบียน & Welcome Coffee' },
      { time: '09:30 - 10:30', title: 'Keynote: The Future of Autonomous AI Agents in SEA', speaker: 'ดร. ภาณุพงศ์ เทคโนโลยี' },
      { time: '10:45 - 12:00', title: 'Panel Discussion: AI Transformation ในองค์กรธุรกิจไทย', speaker: 'CTO จากองค์กรชั้นนำ' },
      { time: '13:00 - 15:30', title: 'Hands-on Workshop: Building Agentic Workflows with Next.js', speaker: 'Lead Architect' },
      { time: '16:00 - 18:00', title: 'Networking Cocktail & Showcase Demo' },
    ]
  },
  {
    id: 'evt-neon-music-fest',
    title: 'Neon Horizon Music & Light Festival 2026',
    description: 'เทศกาลดนตรีและศิลปะแสงสีสุดอลังการใจกลางกรุง สัมผัสประสบการณ์ดนตรี Synthwave, Electronic และ Indie Pop จากศิลปินระดับแถวหน้าทั้งไทยและต่างประเทศ พร้อมโซนถ่ายรูป Interactive Art และ Food Trucks กว่า 40 ร้าน',
    category: 'Music & Festival',
    date: '2026-11-14',
    time: '16:00 - 23:30 น.',
    location: 'Live Park พระราม 9, กรุงเทพมหานคร',
    location_type: 'onsite',
    max_seats: 500,
    booked_seats: 432,
    price: 1290,
    image_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1200&q=80',
    organizer: 'Sonic Pulse Events & Entertainment',
    organizer_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    tags: ['Music', 'Concert', 'Festival', 'EDM', 'Indie'],
    featured: true,
    agenda: [
      { time: '16:00', title: 'เปิดประตูเข้างาน (Gates Open) & Food Zone' },
      { time: '17:00 - 18:30', title: 'Opening Act: The Cosmic Wave & Synth Pop Live' },
      { time: '19:00 - 21:00', title: 'Main Stage Headliner: Electric Dreamers' },
      { time: '21:30 - 23:30', title: 'Grand Finale: Laser Light & DJ Visual Countdown' },
    ]
  },
  {
    id: 'evt-startup-pitch-2026',
    title: 'Southeast Asia Startup Pitch & Venture Day',
    description: 'เวทีประกวดแผนธุรกิจสตาร์ทอัพดาวรุ่ง ชิงเงินรางวัลและโอกาสรับเงินลงทุนรวมกว่า 10,000,000 บาท พบปะกับ Angel Investors และ Venture Capitals จากทั่วภูมิภาคเอเชียตะวันออกเฉียงใต้',
    category: 'Business & Startup',
    date: '2026-10-30',
    time: '10:00 - 17:30 น.',
    location: 'Gaysorn Urban Resort, อาคาร Gaysorn Tower, กรุงเทพฯ',
    location_type: 'onsite',
    max_seats: 120,
    booked_seats: 98,
    price: 490,
    image_url: 'https://images.unsplash.com/photo-1559223607-a43c990c692c?auto=format&fit=crop&w=1200&q=80',
    organizer: 'Venture Leap Asia',
    organizer_avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
    tags: ['Startup', 'Business', 'Investment', 'Pitching', 'Networking'],
    featured: true,
    agenda: [
      { time: '10:00 - 10:30', title: 'Welcome Address & Investment Trend 2026' },
      { time: '10:30 - 12:30', title: 'Top 10 Finalist Pitching (Round 1: Fintech & AI)' },
      { time: '13:30 - 15:30', title: 'Top 10 Finalist Pitching (Round 2: Climate Tech & Health)' },
      { time: '16:00 - 17:30', title: 'Award Ceremony & Private Investor Matchmaking' },
    ]
  },
  {
    id: 'evt-uiux-masterclass',
    title: 'Design System & Micro-Interaction Masterclass (Figma & Code)',
    description: 'เวิร์กช็อปเข้มข้น 1 วันเต็ม ออกแบบ UI Component และ Design System ระดับองค์กร พร้อมการแปลงผลงานไปสู่ Next.js + Tailwind CSS และทำ Interaction Animation สวยสะกดตา',
    category: 'Design & Creative',
    date: '2026-11-07',
    time: '09:30 - 16:30 น.',
    location: 'WeWork อาคาร T-One ชั้น 14 (BTS ทองหล่อ) หรือ Online Live Stream',
    location_type: 'onsite',
    max_seats: 40,
    booked_seats: 36,
    price: 2500,
    image_url: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=1200&q=80',
    organizer: 'Creative Dev Academy',
    organizer_avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80',
    tags: ['UIUX', 'Figma', 'WebDesign', 'TailwindCSS', 'Masterclass'],
    featured: false,
    agenda: [
      { time: '09:30 - 11:30', title: 'Design Token & Scalable Design System in Figma' },
      { time: '11:30 - 12:30', title: 'Modern Typography & Color Accessibility Rules' },
      { time: '13:30 - 15:30', title: 'Coding Components: Next.js + Tailwind + Framer Motion' },
      { time: '15:30 - 16:30', title: 'Portfolio Review & 1-on-1 Feedback Session' },
    ]
  },
  {
    id: 'evt-cybersecurity-bootcamp',
    title: 'Zero Trust & Cloud Security Hands-on Lab',
    description: 'เรียนรู้แนวทางป้องกันภัยคุกคามทางไซเบอร์ยุคใหม่ ทดลองทำ Red Team vs Blue Team Simulation และวางสถาปัตยกรรมความปลอดภัยบน AWS และ Google Cloud',
    category: 'Workshop & Skills',
    date: '2026-11-21',
    time: '13:00 - 17:00 น.',
    location: 'Online Webinar (Zoom Interactive Room)',
    location_type: 'online',
    max_seats: 200,
    booked_seats: 142,
    price: 0,
    image_url: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1200&q=80',
    organizer: 'CyberSec Shield Club',
    organizer_avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=150&q=80',
    tags: ['Cybersecurity', 'Cloud', 'Online', 'Free', 'HandsOn'],
    featured: false,
    agenda: [
      { time: '13:00 - 14:00', title: 'Threat Intelligence Landscape & Attack Vectors 2026' },
      { time: '14:15 - 15:45', title: 'Live Lab: Penetration Testing & API Defense' },
      { time: '16:00 - 17:00', title: 'Zero Trust Implementation Best Practices & Q&A' },
    ]
  },
  {
    id: 'evt-bangkok-night-run',
    title: 'Bangkok City Neon Night Run 2026 (10K / 5K)',
    description: 'งานวิ่งกลางคืนสไตล์นีออนเรืองแสง วิ่งชมความงามของสะพานพระราม 8 และทิวทัศน์ริมแม่น้ำเจ้าพระยา พร้อมรับเหรียญที่ระลึกเรืองแสง เสื้อวิ่งดรายฟิต และ Mini Concert หลังเส้นชัย',
    category: 'Health & Sport',
    date: '2026-11-28',
    time: '18:30 - 22:00 น.',
    location: 'สวนหลวง ร.9 และบริเวณสะพานพระราม 8 กรุงเทพฯ',
    location_type: 'onsite',
    max_seats: 800,
    booked_seats: 615,
    price: 650,
    image_url: 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?auto=format&fit=crop&w=1200&q=80',
    organizer: 'Active Life Run Club Thailand',
    organizer_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    tags: ['Running', 'Sport', 'NightRun', 'Health', 'Bangkok'],
    featured: false,
    agenda: [
      { time: '18:30 - 19:15', title: 'Check-in, Body Glow Painting & Warm-up' },
      { time: '19:30', title: 'ปล่อยตัวระยะ 10 KM (Mini Marathon)' },
      { time: '19:45', title: 'ปล่อยตัวระยะ 5 KM (Fun Run)' },
      { time: '21:00 - 22:00', title: 'พิธีมอบถ้วยรางวัล & After Run Party' },
    ]
  }
];

export const CATEGORIES_LIST = [
  { id: 'all', name: 'ทั้งหมด (All)', icon: 'Sparkles', color: 'from-purple-500 to-indigo-500' },
  { id: 'Tech & AI', name: 'เทคโนโลยี & AI', icon: 'Cpu', color: 'from-blue-500 to-cyan-500' },
  { id: 'Music & Festival', name: 'ดนตรี & คอนเสิร์ต', icon: 'Music', color: 'from-pink-500 to-rose-500' },
  { id: 'Business & Startup', name: 'ธุรกิจ & สตาร์ทอัพ', icon: 'Briefcase', color: 'from-emerald-500 to-teal-500' },
  { id: 'Workshop & Skills', name: 'เวิร์กช็อป & การเรียนรู้', icon: 'BookOpen', color: 'from-amber-500 to-orange-500' },
  { id: 'Design & Creative', name: 'ดีไซน์ & ครีเอทีฟ', icon: 'Palette', color: 'from-purple-500 to-pink-500' },
  { id: 'Health & Sport', name: 'กีฬา & สุขภาพ', icon: 'Activity', color: 'from-cyan-500 to-blue-500' },
];
